Repository brain-tec/web, pull requests merged in 2020-01, with the labels that each got.

#473 Syncing from upstream OCA/web (10.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_unclickable/odoo/__init__.py
  setup/web_unclickable/odoo/addons/__init__.py
  setup/web_unclickable/odoo/addons/web_unclickable
  setup/web_unclickable/setup.py
  web_unclickable/README.rst
  web_unclickable/__init__.py
  web_unclickable/__manifest__.py
  web_unclickable/readme/CONTRIBUTORS.rst
  web_unclickable/readme/DESCRIPTION.rst
  web_unclickable/readme/USAGE.rst
  web_unclickable/static/description/icon.png
  web_unclickable/static/description/index.html
  web_unclickable/static/src/css/web_template.css
  web_unclickable/views/web_template.xml
Labels: 10.0

#474 Syncing from upstream OCA/web (13.0)
  .isort.cfg
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_notify/odoo/addons/web_notify
  setup/web_notify/setup.py
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/i18n/da.po
  web_notify/i18n/de.po
  web_notify/i18n/es.po
  web_notify/i18n/hr.po
  web_notify/i18n/nl_NL.po
  web_notify/i18n/pt_BR.po
  web_notify/i18n/web_notify.pot
  web_notify/i18n/zh_CN.po
  web_notify/models/__init__.py
  web_notify/models/res_users.py
  web_notify/readme/CONTRIBUTORS.rst
  web_notify/readme/DESCRIPTION.rst
  web_notify/readme/INSTALL.rst
  web_notify/readme/USAGE.rst
  web_notify/static/description/icon.png
  web_notify/static/description/index.html
  web_notify/static/description/notifications_screenshot.png
  web_notify/static/description/test_notifications_demo.png
  web_notify/static/src/js/web_client.js
  web_notify/static/src/js/widgets/notification.js
  web_notify/static/src/scss/webclient.scss
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
  web_notify/views/web_notify.xml
Labels: 13.0

#475 Syncing from upstream OCA/web (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_ir_actions_act_view_reload/odoo/addons/web_ir_actions_act_view_reload
  setup/web_ir_actions_act_view_reload/setup.py
  web_ir_actions_act_view_reload/README.rst
  web_ir_actions_act_view_reload/__init__.py
  web_ir_actions_act_view_reload/__manifest__.py
  web_ir_actions_act_view_reload/i18n/web_ir_actions_act_view_reload.pot
  web_ir_actions_act_view_reload/i18n/zh_CN.po
  web_ir_actions_act_view_reload/readme/CONTRIBUTORS.rst
  web_ir_actions_act_view_reload/readme/DESCRIPTION.rst
  web_ir_actions_act_view_reload/readme/USAGE.rst
  web_ir_actions_act_view_reload/static/description/icon.png
  web_ir_actions_act_view_reload/static/description/index.html
  web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.js
  web_ir_actions_act_view_reload/views/web_ir_actions_act_view_reload.xml
Labels: 13.0

#476 Syncing from upstream OCA/web (12.0)
  web_advanced_search/README.rst
  web_advanced_search/__manifest__.py
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/static/description/index.html
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: 12.0

#477 Syncing from upstream OCA/web (12.0)
  web_responsive/__manifest__.py
  web_responsive/static/src/js/web_responsive.js
Labels: 12.0

#478 Syncing from upstream OCA/web (13.0)
  web_notify/i18n/da.po
  web_notify/i18n/de.po
  web_notify/i18n/es.po
  web_notify/i18n/hr.po
  web_notify/i18n/nl_NL.po
  web_notify/i18n/pt_BR.po
  web_notify/i18n/zh_CN.po
  web_responsive/__manifest__.py
  web_responsive/static/src/css/web_responsive.scss
Labels: 13.0

#479 Syncing from upstream OCA/web (12.0)
  web_switch_context_warning/i18n/fr.po
Labels: 12.0

#481 Syncing from upstream OCA/web (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_domain_field/odoo/addons/web_domain_field
  setup/web_domain_field/setup.py
  web_domain_field/README.rst
  web_domain_field/__init__.py
  web_domain_field/__manifest__.py
  web_domain_field/i18n/web_domain_field.pot
  web_domain_field/static/description/icon.png
  web_domain_field/static/src/js/pyeval.js
  web_domain_field/views/web_domain_field.xml
Labels: 13.0

#482 13.0 mig web no bubble
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/readme/CONTRIBUTORS.rst
  web_no_bubble/readme/DESCRIPTION.rst
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
  web_no_bubble/views/web_no_bubble.xml
Labels: 13.0.project_sv_559

#483 Syncing from upstream OCA/web (12.0)
  web_responsive/__manifest__.py
  web_responsive/static/src/css/web_responsive.scss
Labels: 12.0

#484 Syncing from upstream OCA/web (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_no_bubble/odoo/addons/web_no_bubble
  setup/web_no_bubble/setup.py
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/readme/CONTRIBUTORS.rst
  web_no_bubble/readme/DESCRIPTION.rst
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
  web_no_bubble/views/web_no_bubble.xml
Labels: 13.0

#485 Syncing from upstream OCA/web (13.0)
  .editorconfig
  .eslintrc
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  .travis.yml
  web_decimal_numpad_dot/static/src/js/numpad_dot.js
  web_decimal_numpad_dot/views/web_decimal_numpad_dot.xml
  web_dialog_size/static/src/js/web_dialog_size.js
  web_dialog_size/static/src/scss/web_dialog_size.scss
  web_dialog_size/static/src/xml/web_dialog_size.xml
  web_dialog_size/templates/assets.xml
  web_domain_field/i18n/web_domain_field.pot
  web_domain_field/static/lib/js/pyeval.js
  web_domain_field/views/web_domain_field.xml
  web_environment_ribbon/data/ribbon_data.xml
  web_environment_ribbon/static/src/css/ribbon.css
  web_environment_ribbon/static/src/js/ribbon.js
  web_environment_ribbon/view/base_view.xml
  web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.js
  web_ir_actions_act_view_reload/views/web_ir_actions_act_view_reload.xml
  web_no_bubble/static/src/css/web_no_bubble.scss
  web_no_bubble/views/web_no_bubble.xml
  web_notify/static/src/js/web_client.js
  web_notify/static/src/js/widgets/notification.js
  web_notify/static/src/scss/webclient.scss
  web_notify/views/res_users_demo.xml
  web_notify/views/web_notify.xml
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/js/web_responsive.js
  web_responsive/static/src/xml/apps.xml
  web_responsive/static/src/xml/document_viewer.xml
  web_responsive/static/src/xml/form_view.xml
  web_responsive/static/src/xml/navbar.xml
  web_responsive/views/assets.xml
  web_responsive/views/res_users.xml
  web_responsive/views/web.xml
  web_tree_many2one_clickable/static/src/css/web_tree_many2one_clickable.scss
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
  web_tree_many2one_clickable/views/assets.xml
  web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.js
  web_widget_bokeh_chart/static/src/scss/custom-bokeh.scss
  web_widget_bokeh_chart/views/web_widget_bokeh_chart.xml
Labels: 13.0
