Repository brain-tec/web, pull requests merged in 2020-02, with the labels that each got.

#486 Syncing from upstream OCA/web (12.0)
  web_tree_many2one_clickable/__manifest__.py
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
Labels: 12.0

#488 Syncing from upstream OCA/web (12.0)
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: 12.0

#489 Syncing from upstream OCA/web (12.0)
  web_action_conditionable/i18n/es.po
  web_timeline/i18n/es.po
Labels: 12.0

#490 Syncing from upstream OCA/web (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_image_download/odoo/addons/web_widget_image_download
  setup/web_widget_image_download/setup.py
  web_widget_image_download/README.rst
  web_widget_image_download/__init__.py
  web_widget_image_download/__manifest__.py
  web_widget_image_download/i18n/hr.po
  web_widget_image_download/i18n/lt.po
  web_widget_image_download/i18n/nl_NL.po
  web_widget_image_download/i18n/pt.po
  web_widget_image_download/i18n/web_widget_image_download.pot
  web_widget_image_download/i18n/zh_CN.po
  web_widget_image_download/readme/CONTRIBUTORS.rst
  web_widget_image_download/readme/DESCRIPTION.rst
  web_widget_image_download/readme/USAGE.rst
  web_widget_image_download/static/description/icon.png
  web_widget_image_download/static/description/index.html
  web_widget_image_download/static/src/js/web_widget_image_download.js
  web_widget_image_download/static/src/scss/web_widget_image_download.scss
  web_widget_image_download/static/src/xml/web_widget_image_download.xml
  web_widget_image_download/views/assets.xml
Labels: 13.0

#491 Syncing from upstream OCA/web (11.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_text_markdown/odoo/addons/web_widget_text_markdown
  setup/web_widget_text_markdown/setup.cfg
  setup/web_widget_text_markdown/setup.py
  web_widget_text_markdown/README.rst
  web_widget_text_markdown/__init__.py
  web_widget_text_markdown/__manifest__.py
  web_widget_text_markdown/demo/bootstrap_markdown.xml
  web_widget_text_markdown/i18n/ar.po
  web_widget_text_markdown/i18n/de.po
  web_widget_text_markdown/i18n/es.po
  web_widget_text_markdown/i18n/fi.po
  web_widget_text_markdown/i18n/fr.po
  web_widget_text_markdown/i18n/pt_BR.po
  web_widget_text_markdown/i18n/sl.po
  web_widget_text_markdown/i18n/tr.po
  web_widget_text_markdown/i18n/web_widget_text_markdown.pot
  web_widget_text_markdown/readme/CONTRIBUTORS.rst
  web_widget_text_markdown/readme/CREDITS.rst
  web_widget_text_markdown/readme/DESCRIPTION.rst
  web_widget_text_markdown/readme/ROADMAP.rst
  web_widget_text_markdown/readme/USAGE.rst
  web_widget_text_markdown/static/description/icon.png
  web_widget_text_markdown/static/description/index.html
  web_widget_text_markdown/static/src/js/web_widget_text_markdown.js
  web_widget_text_markdown/static/src/less/web_widget_text_markdown.less
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.js
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.min.css
  web_widget_text_markdown/static/src/lib/dropzone.js
  web_widget_text_markdown/static/src/lib/marked.js
  web_widget_text_markdown/static/tests/js/web_widget_text_markdown.js
  web_widget_text_markdown/views/assets.xml
Labels: 11.0

#492 Syncing from upstream OCA/web (12.0)
  web_favicon/i18n/ca.po
  web_favicon/i18n/ca_ES.po
Labels: 12.0

#493 Syncing from upstream OCA/web (12.0)
  web_edit_user_filter/i18n/da.po
  web_export_view/i18n/da.po
  web_notify/i18n/da.po
  web_responsive/i18n/da.po
  web_widget_plotly_chart/i18n/da.po
Labels: 12.0

#494 Syncing from upstream OCA/web (12.0)
  web_responsive/__manifest__.py
  web_responsive/static/src/css/web_responsive.scss
Labels: 12.0

#495 Syncing from upstream OCA/web (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_open_tab/odoo/addons/web_widget_open_tab
  setup/web_widget_open_tab/setup.py
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/i18n/web_widget_open_tab.pot
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/DESCRIPTION.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/widget.js
  web_widget_open_tab/static/src/less/open_tab.less
  web_widget_open_tab/views/assets.xml
Labels: 12.0

#496 Syncing from upstream OCA/web (13.0)
  web_domain_field/views/web_domain_field.xml
  web_widget_image_download/i18n/hr.po
  web_widget_image_download/i18n/lt.po
  web_widget_image_download/i18n/nl_NL.po
  web_widget_image_download/i18n/pt.po
  web_widget_image_download/i18n/zh_CN.po
Labels: 13.0

#497 Syncing from upstream OCA/web (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_numeric_step/odoo/addons/web_widget_numeric_step
  setup/web_widget_numeric_step/setup.py
  web_responsive/__manifest__.py
  web_responsive/static/src/js/web_responsive.js
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/__init__.py
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/demo/res_users_view.xml
  web_widget_numeric_step/i18n/fr.po
  web_widget_numeric_step/i18n/web_widget_numeric_step.pot
  web_widget_numeric_step/readme/CONTRIBUTORS.rst
  web_widget_numeric_step/readme/DESCRIPTION.rst
  web_widget_numeric_step/readme/USAGE.rst
  web_widget_numeric_step/static/description/add_two_buttons.png
  web_widget_numeric_step/static/description/icon.png
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/description/step0,25andlimits.gif
  web_widget_numeric_step/static/description/step10_limit15_placeholder117_with_onchange.gif
  web_widget_numeric_step/static/src/css/numeric_step.scss
  web_widget_numeric_step/static/src/js/numeric_step.js
  web_widget_numeric_step/static/src/xml/numeric_step.xml
  web_widget_numeric_step/view/assets.xml
Labels: 12.0

#500 12.0 mig web widget timepicker
  web_widget_timepicker/README.rst
  web_widget_timepicker/__init__.py
  web_widget_timepicker/__manifest__.py
  web_widget_timepicker/i18n/web_widget_timepicker.pot
  web_widget_timepicker/readme/CONTRIBUTORS.rst
  web_widget_timepicker/readme/CREDITS.rst
  web_widget_timepicker/readme/DESCRIPTION.rst
  web_widget_timepicker/readme/USAGE.rst
  web_widget_timepicker/static/description/icon.png
  web_widget_timepicker/static/description/index.html
  web_widget_timepicker/static/src/js/web_widget_timepicker.js
  web_widget_timepicker/views/web_widget_timepicker_assets.xml
Labels: 12.0.project_gv_545

#501 Syncing from upstream OCA/web (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_translate_dialog/odoo/addons/web_translate_dialog
  setup/web_translate_dialog/setup.py
  web_translate_dialog/README.rst
  web_translate_dialog/__init__.py
  web_translate_dialog/__manifest__.py
  web_translate_dialog/i18n/ar.po
  web_translate_dialog/i18n/de.po
  web_translate_dialog/i18n/es.po
  web_translate_dialog/i18n/fi.po
  web_translate_dialog/i18n/fr.po
  web_translate_dialog/i18n/hr.po
  web_translate_dialog/i18n/it.po
  web_translate_dialog/i18n/nl.po
  web_translate_dialog/i18n/nl_NL.po
  web_translate_dialog/i18n/pt_BR.po
  web_translate_dialog/i18n/sl.po
  web_translate_dialog/i18n/tr.po
  web_translate_dialog/i18n/web_translate_dialog.pot
  web_translate_dialog/models/__init__.py
  web_translate_dialog/models/base.py
  web_translate_dialog/models/res_lang.py
  web_translate_dialog/readme/CONTRIBUTORS.rst
  web_translate_dialog/readme/DESCRIPTION.rst
  web_translate_dialog/readme/USAGE.rst
  web_translate_dialog/static/description/icon.png
  web_translate_dialog/static/description/index.html
  web_translate_dialog/static/src/css/base.css
  web_translate_dialog/static/src/js/web_translate_dialog.js
  web_translate_dialog/static/src/xml/base.xml
  web_translate_dialog/views/res_lang.xml
  web_translate_dialog/views/web_translate.xml
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: 12.0

#502 Syncing from upstream OCA/web (13.0)
  web_responsive/__manifest__.py
  web_responsive/static/src/js/web_responsive.js
Labels: 13.0
