Repository brain-tec/web, pull requests merged in 2021-10, with the labels that each got.

#758 Syncing from upstream OCA/web (12.0)
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/__manifest__.py
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
Labels: 12.0

#759 Syncing from upstream OCA/web (14.0)
  web_advanced_search/i18n/it.po
Labels: 14.0

#760 Merging 12.0 into 12.0.project_MI_465
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_one2many_product_picker_sale_stock_available_info_popup/odoo/addons/web_widget_one2many_product_picker_sale_stock_available_info_popup
  setup/web_widget_one2many_product_picker_sale_stock_available_info_popup/setup.py
  web_widget_digitized_signature/__manifest__.py
  web_widget_digitized_signature/models/mail_thread.py
  web_widget_digitized_signature/models/res_users.py
  web_widget_digitized_signature/tests/test_signature_tracking.py
  web_widget_digitized_signature/views/res_users_view.xml
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/__manifest__.py
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker_sale_stock_available_info_popup/README.rst
  web_widget_one2many_product_picker_sale_stock_available_info_popup/__init__.py
  web_widget_one2many_product_picker_sale_stock_available_info_popup/__manifest__.py
  web_widget_one2many_product_picker_sale_stock_available_info_popup/i18n/web_widget_one2many_product_picker_sale_stock_available_info_popup.pot
  web_widget_one2many_product_picker_sale_stock_available_info_popup/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker_sale_stock_available_info_popup/readme/DESCRIPTION.rst
  web_widget_one2many_product_picker_sale_stock_available_info_popup/static/description/icon.png
  web_widget_one2many_product_picker_sale_stock_available_info_popup/static/description/index.html
  web_widget_one2many_product_picker_sale_stock_available_info_popup/static/src/js/views/abstract_view.js
  web_widget_one2many_product_picker_sale_stock_available_info_popup/templates/assets.xml
Labels: 12.0.project_mi_465

#761 Syncing from upstream OCA/web (12.0)
  web_translate_dialog/__manifest__.py
  web_translate_dialog/i18n/ar.po
  web_translate_dialog/i18n/ca.po
  web_translate_dialog/i18n/de.po
  web_translate_dialog/i18n/es.po
  web_translate_dialog/i18n/fi.po
  web_translate_dialog/i18n/fr.po
  web_translate_dialog/i18n/hr.po
  web_translate_dialog/i18n/it.po
  web_translate_dialog/i18n/nl.po
  web_translate_dialog/i18n/nl_NL.po
  web_translate_dialog/i18n/pt_BR.po
  web_translate_dialog/i18n/sl.po
  web_translate_dialog/i18n/tr.po
  web_translate_dialog/i18n/web_translate_dialog.pot
  web_translate_dialog/static/src/js/web_translate_dialog.js
Labels: 12.0

#762 Syncing from upstream OCA/web (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_open_tab/odoo/addons/web_widget_open_tab
  setup/web_widget_open_tab/setup.py
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/i18n/ca.po
  web_widget_open_tab/i18n/es.po
  web_widget_open_tab/i18n/pt_BR.po
  web_widget_open_tab/i18n/web_widget_open_tab.pot
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/DESCRIPTION.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/widget.js
  web_widget_open_tab/templates/assets.xml
Labels: 14.0

#782 Syncing from upstream OCA/web (13.0)
  README.md
  web_drop_target/__manifest__.py
  web_drop_target/static/src/js/web_drop_target.js
Labels: 13.0
