Repository brain-tec/web, pull requests merged in 2021-06, with the labels that each got.

#703 Syncing from upstream OCA/web (12.0)
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/__manifest__.py
  web_widget_one2many_product_picker/i18n/ca.po
  web_widget_one2many_product_picker/i18n/es.po
  web_widget_one2many_product_picker/i18n/pt_BR.po
  web_widget_one2many_product_picker/i18n/web_widget_one2many_product_picker.pot
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/views/basic_controller.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker/templates/assets.xml
Labels: 12.0

#704 Syncing from upstream OCA/web (13.0)
  web_advanced_search/i18n/ca.po
  web_advanced_search/i18n/es_PA.po
  web_decimal_numpad_dot/i18n/ca.po
Labels: 13.0

#705 Updating from latest OCA 12.0
  web_pwa_oca/static/description/index.html
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/__manifest__.py
  web_widget_one2many_product_picker/i18n/ca.po
  web_widget_one2many_product_picker/i18n/es.po
  web_widget_one2many_product_picker/i18n/pt_BR.po
  web_widget_one2many_product_picker/i18n/web_widget_one2many_product_picker.pot
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/views/basic_controller.js
  web_widget_one2many_product_picker/static/src/js/views/basic_model.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker/templates/assets.xml
Labels: 12.0.project_mi_465

#706 Syncing from upstream OCA/web (12.0)
  web_company_color/__manifest__.py
  web_company_color/i18n/ca.po
  web_company_color/i18n/de.po
  web_company_color/i18n/es.po
  web_company_color/i18n/es_ES.po
  web_company_color/i18n/fr.po
  web_company_color/i18n/hr.po
  web_company_color/i18n/pt_BR.po
  web_company_color/i18n/web_company_color.pot
  web_company_color/i18n/zh_CN.po
  web_company_color/models/res_company.py
  web_company_color/view/res_company.xml
Labels: 12.0

#707 Syncing from upstream OCA/web (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_translate_dialog/odoo/addons/web_translate_dialog
  setup/web_translate_dialog/setup.py
  web_translate_dialog/README.rst
  web_translate_dialog/__init__.py
  web_translate_dialog/__manifest__.py
  web_translate_dialog/i18n/ar.po
  web_translate_dialog/i18n/de.po
  web_translate_dialog/i18n/es.po
  web_translate_dialog/i18n/fi.po
  web_translate_dialog/i18n/fr.po
  web_translate_dialog/i18n/hr.po
  web_translate_dialog/i18n/it.po
  web_translate_dialog/i18n/nl.po
  web_translate_dialog/i18n/nl_NL.po
  web_translate_dialog/i18n/pt_BR.po
  web_translate_dialog/i18n/sl.po
  web_translate_dialog/i18n/tr.po
  web_translate_dialog/i18n/web_translate_dialog.pot
  web_translate_dialog/models/__init__.py
  web_translate_dialog/models/base.py
  web_translate_dialog/models/res_lang.py
  web_translate_dialog/readme/CONTRIBUTORS.rst
  web_translate_dialog/readme/DESCRIPTION.rst
  web_translate_dialog/readme/USAGE.rst
  web_translate_dialog/static/description/icon.png
  web_translate_dialog/static/description/index.html
  web_translate_dialog/static/src/css/base.css
  web_translate_dialog/static/src/js/web_translate_dialog.js
  web_translate_dialog/static/src/xml/base.xml
  web_translate_dialog/tests/__init__.py
  web_translate_dialog/tests/test_web_translate_dialog.py
  web_translate_dialog/views/res_lang.xml
  web_translate_dialog/views/web_translate.xml
Labels: 13.0

#708 Syncing from upstream OCA/web (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_group_expand/odoo/addons/web_group_expand
  setup/web_group_expand/setup.py
  web_group_expand/README.rst
  web_group_expand/__init__.py
  web_group_expand/__manifest__.py
  web_group_expand/i18n/ca.po
  web_group_expand/i18n/es.po
  web_group_expand/i18n/nl.po
  web_group_expand/i18n/pt_BR.po
  web_group_expand/i18n/web_group_expand.pot
  web_group_expand/readme/CONTRIBUTORS.rst
  web_group_expand/readme/DESCRIPTION.rst
  web_group_expand/static/description/icon.png
  web_group_expand/static/description/index.html
  web_group_expand/static/src/js/web_group_expand.js
  web_group_expand/static/src/xml/expand_buttons.xml
  web_group_expand/views/templates.xml
Labels: 14.0

#709 Syncing from upstream OCA/web (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_no_bubble/odoo/addons/web_no_bubble
  setup/web_no_bubble/setup.py
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/es.po
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/readme/CONTRIBUTORS.rst
  web_no_bubble/readme/DESCRIPTION.rst
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
  web_no_bubble/views/web_no_bubble.xml
Labels: 14.0

#710 Syncing from upstream OCA/web (13.0)
  .prettierrc.yml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_send_message_popup/odoo/addons/web_send_message_popup
  setup/web_send_message_popup/setup.py
  web_responsive/__manifest__.py
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/js/discuss.js
  web_send_message_popup/README.rst
  web_send_message_popup/__init__.py
  web_send_message_popup/__manifest__.py
  web_send_message_popup/i18n/web_send_message_popup.pot
  web_send_message_popup/readme/CONTRIBUTORS.rst
  web_send_message_popup/readme/DESCRIPTION.rst
  web_send_message_popup/static/description/icon.png
  web_send_message_popup/static/description/index.html
  web_send_message_popup/static/src/js/chatter.js
  web_send_message_popup/templates/assets.xml
Labels: 13.0

#711 Backmerge from 12.0 into 12.0.project_MI_465
  web_company_color/__manifest__.py
  web_company_color/i18n/ca.po
  web_company_color/i18n/de.po
  web_company_color/i18n/es.po
  web_company_color/i18n/es_ES.po
  web_company_color/i18n/fr.po
  web_company_color/i18n/hr.po
  web_company_color/i18n/pt_BR.po
  web_company_color/i18n/web_company_color.pot
  web_company_color/i18n/zh_CN.po
  web_company_color/models/res_company.py
  web_company_color/view/res_company.xml
Labels: 12.0.project_mi_465

#712 Syncing from upstream OCA/web (12.0)
  web_responsive/i18n/fr.po
Labels: 12.0

#713 Syncing from upstream OCA/web (14.0)
  web_responsive/i18n/fr.po
Labels: 14.0
