Repository brain-tec/web, pull requests merged in 2022-09, with the labels that each got.

#921 Syncing from upstream OCA/web (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_copy_confirm/odoo/addons/web_copy_confirm
  setup/web_copy_confirm/setup.py
  web_copy_confirm/README.rst
  web_copy_confirm/__init__.py
  web_copy_confirm/__manifest__.py
  web_copy_confirm/i18n/de.po
  web_copy_confirm/i18n/web_copy_confirm.pot
  web_copy_confirm/readme/CONTRIBUTORS.rst
  web_copy_confirm/readme/DESCRIPTION.rst
  web_copy_confirm/readme/HISTORY.rst
  web_copy_confirm/readme/newsfragments/.gitkeep
  web_copy_confirm/static/description/icon.png
  web_copy_confirm/static/description/index.html
  web_copy_confirm/static/src/js/web_copy_confirm.js
  web_copy_confirm/static/tests/confirm_tests.js
Labels: 15.0

#922 Syncing from upstream OCA/web (11.0)
  web_export_view/__manifest__.py
  web_export_view/static/src/js/web_export_view.js
Labels: 11.0

#923 Syncing from upstream OCA/web (12.0)
  README.md
  web_export_view/__manifest__.py
  web_export_view/static/src/js/web_export_view.js
Labels: 12.0

#924 [t131818] import open PR of mig web notify
  setup/web_notify/odoo/addons/web_notify
  setup/web_notify/setup.py
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/i18n/da.po
  web_notify/i18n/de.po
  web_notify/i18n/es.po
  web_notify/i18n/hr.po
  web_notify/i18n/nl.po
  web_notify/i18n/nl_NL.po
  web_notify/i18n/pt_BR.po
  web_notify/i18n/web_notify.pot
  web_notify/i18n/zh_CN.po
  web_notify/models/__init__.py
  web_notify/models/res_users.py
  web_notify/readme/CONTRIBUTORS.rst
  web_notify/readme/DESCRIPTION.rst
  web_notify/readme/INSTALL.rst
  web_notify/readme/USAGE.rst
  web_notify/static/description/icon.png
  web_notify/static/description/index.html
  web_notify/static/description/notifications_screenshot.png
  web_notify/static/description/test_notifications_demo.png
  web_notify/static/src/js/services/notification.js
  web_notify/static/src/js/services/notification_services.js
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
Labels: 15.0.project_sy_639.t131818

#926 Syncing from upstream OCA/web (15.0)
  README.md
  web_advanced_search/__manifest__.py
  web_advanced_search/static/src/js/legacy/CustomFilterItem.esm.js
  web_advanced_search/static/src/js/owl/CustomFilterItem.esm.js
Labels: 15.0

#927 Syncing from upstream OCA/web (13.0)
  web_disable_export_group/i18n/es.po
Labels: 13.0

#928 Syncing from upstream OCA/web (14.0)
  web_company_color/i18n/fr.po
Labels: 14.0

#929 Syncing from upstream OCA/web (12.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/static/src/css/web_responsive.scss
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_renderer.js
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
  web_widget_x2many_2d_matrix_example/__manifest__.py
  web_widget_x2many_2d_matrix_example/i18n/ca.po
  web_widget_x2many_2d_matrix_example/i18n/es.po
  web_widget_x2many_2d_matrix_example/i18n/pt_BR.po
  web_widget_x2many_2d_matrix_example/i18n/web_widget_x2many_2d_matrix_example.pot
  web_widget_x2many_2d_matrix_example/i18n/zh_CN.po
  web_widget_x2many_2d_matrix_example/models/__init__.py
  web_widget_x2many_2d_matrix_example/models/res_users.py
  web_widget_x2many_2d_matrix_example/models/x2m_demo.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.xml
Labels: 12.0

#931 Syncing from upstream OCA/web (14.0)
  web_company_color/i18n/it.po
  web_responsive/i18n/it.po
Labels: 14.0

#932 Syncing from upstream OCA/web (13.0)
  README.md
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/static/description/index.html
  web_refresher/static/src/js/refresher.js
  web_refresher/static/src/xml/refresher.xml
Labels: 13.0

#933 Syncing from upstream OCA/web (15.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/static/src/legacy/js/kanban_renderer_mobile.js
Labels: 15.0

#934 Syncing from upstream OCA/web (15.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/i18n/ar.po
  web_responsive/i18n/ca.po
  web_responsive/i18n/da.po
  web_responsive/i18n/de.po
  web_responsive/i18n/es.po
  web_responsive/i18n/fr.po
  web_responsive/i18n/fr_FR.po
  web_responsive/i18n/hr.po
  web_responsive/i18n/nl.po
  web_responsive/i18n/pl.po
  web_responsive/i18n/pt.po
  web_responsive/i18n/pt_BR.po
  web_responsive/i18n/ru.po
  web_responsive/i18n/tr.po
  web_responsive/i18n/web_responsive.pot
  web_responsive/i18n/zh_CN.po
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
  web_responsive/static/src/components/apps_menu/apps_menu.xml
Labels: 15.0

#935 Syncing from upstream OCA/web (14.0)
  README.md
  web_drop_target/__manifest__.py
  web_drop_target/static/src/js/web_drop_target.js
Labels: 14.0
