Repository brain-tec/web, pull requests merged in 2023-10, with the labels that each got.

#1113 Syncing from upstream OCA/web (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_remote_measure/odoo/addons/web_widget_remote_measure
  setup/web_widget_remote_measure/setup.py
  web_widget_remote_measure/README.rst
  web_widget_remote_measure/__init__.py
  web_widget_remote_measure/__manifest__.py
  web_widget_remote_measure/i18n/web_widget_remote_measure.pot
  web_widget_remote_measure/models/__init__.py
  web_widget_remote_measure/models/remote_measure_device.py
  web_widget_remote_measure/models/res_users.py
  web_widget_remote_measure/readme/CONFIGURE.rst
  web_widget_remote_measure/readme/CONTRIBUTORS.rst
  web_widget_remote_measure/readme/DESCRIPTION.rst
  web_widget_remote_measure/readme/ROADMAP.rst
  web_widget_remote_measure/readme/USAGE.rst
  web_widget_remote_measure/security/ir.model.access.csv
  web_widget_remote_measure/static/description/icon.png
  web_widget_remote_measure/static/description/index.html
  web_widget_remote_measure/static/src/js/remote_measure_device_kanban_widget.esm.js
  web_widget_remote_measure/static/src/js/remote_measure_widget.esm.js
  web_widget_remote_measure/static/src/scss/remote_measure_widget.scss
  web_widget_remote_measure/static/src/xml/measure_device_status.xml
  web_widget_remote_measure/views/remote_measure_device_views.xml
  web_widget_remote_measure/views/res_users_views.xml
Labels: 15.0

#1114 Syncing from upstream OCA/web (14.0)
  README.md
  web_field_required_invisible_manager/README.rst
  web_field_required_invisible_manager/__manifest__.py
  web_field_required_invisible_manager/models/custom_field_restriction.py
  web_field_required_invisible_manager/static/description/index.html
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
Labels: 14.0

#1115 Syncing from upstream OCA/web (14.0)
  README.md
  web_field_required_invisible_manager/README.rst
  web_field_required_invisible_manager/__manifest__.py
  web_field_required_invisible_manager/models/custom_field_restriction.py
  web_field_required_invisible_manager/readme/ROADMAP.rst
  web_field_required_invisible_manager/static/description/index.html
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
Labels: 14.0

#1116 Syncing from upstream OCA/web (16.0)
  README.md
  web_remember_tree_column_width/README.rst
  web_remember_tree_column_width/__manifest__.py
  web_remember_tree_column_width/static/description/index.html
  web_remember_tree_column_width/static/src/js/list_renderer.esm.js
Labels: 16.0

#1117 [t141783] Backmerge web select all companies
  setup/web_select_all_companies/odoo/addons/web_select_all_companies
  setup/web_select_all_companies/setup.py
  web_select_all_companies/README.rst
  web_select_all_companies/__init__.py
  web_select_all_companies/__manifest__.py
  web_select_all_companies/i18n/fr.po
  web_select_all_companies/i18n/web_select_all_companies.pot
  web_select_all_companies/readme/CONTRIBUTORS.rst
  web_select_all_companies/readme/DESCRIPTION.rst
  web_select_all_companies/static/description/icon.png
  web_select_all_companies/static/description/index.html
  web_select_all_companies/static/description/select_all_companies.gif
  web_select_all_companies/static/src/js/switch_all_company_menu.esm.js
  web_select_all_companies/static/src/scss/switch_all_company_menu.scss
  web_select_all_companies/static/src/xml/switch_all_company_menu.xml
Labels: 15.0.project_re_670

#1118 Syncing from upstream OCA/web (14.0)
  README.md
  web_field_required_invisible_manager/README.rst
  web_field_required_invisible_manager/__manifest__.py
  web_field_required_invisible_manager/models/models.py
  web_field_required_invisible_manager/static/description/index.html
Labels: 14.0

#1125 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
  web_responsive/static/src/components/apps_menu/apps_menu.scss
Labels: 16.0

#1126 Syncing from upstream OCA/web (16.0)
  web_widget_numeric_step/i18n/es.po
Labels: 16.0

#1127 Syncing from upstream OCA/web (16.0)
  web_responsive/i18n/pt_BR.po
Labels: 16.0

#1128 Syncing from upstream OCA/web (14.0)
  README.md
  web_create_write_confirm/README.rst
  web_create_write_confirm/__manifest__.py
  web_create_write_confirm/models/base.py
  web_create_write_confirm/models/popup_message.py
  web_create_write_confirm/readme/USAGE.rst
  web_create_write_confirm/static/description/index.html
  web_create_write_confirm/static/src/js/pop_up_confirmation.js
  web_create_write_confirm/tests/test_base_model.py
Labels: 14.0

#1129 Syncing from upstream OCA/web (13.0)
  README.md
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
Labels: 13.0

#1131 Syncing from upstream OCA/web (15.0)
  README.md
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
Labels: 15.0

#1132 Syncing from upstream OCA/web (15.0)
  README.md
  web_advanced_search/README.rst
  web_advanced_search/__manifest__.py
  web_advanced_search/i18n/web_advanced_search.pot
  web_advanced_search/static/description/index.html
  web_advanced_search/static/src/js/DomainSelector.esm.js
Labels: 15.0

#1133 Syncing from upstream OCA/web (14.0)
  README.md
  web_edit_user_filter/README.rst
  web_edit_user_filter/__manifest__.py
  web_edit_user_filter/static/description/index.html
  web_edit_user_filter/static/src/js/backend.js
Labels: 14.0

#1134 Syncing from upstream OCA/web (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_uom/odoo/addons/web_widget_uom
  setup/web_widget_uom/setup.py
  web_widget_uom/README.rst
  web_widget_uom/__init__.py
  web_widget_uom/__manifest__.py
  web_widget_uom/i18n/it.po
  web_widget_uom/i18n/web_widget_uom.pot
  web_widget_uom/models/__init__.py
  web_widget_uom/models/uom_uom.py
  web_widget_uom/readme/CONTRIBUTORS.rst
  web_widget_uom/readme/DESCRIPTION.rst
  web_widget_uom/readme/ROADMAP.rst
  web_widget_uom/readme/USAGE.rst
  web_widget_uom/static/description/UoMDecimalPlaces.png
  web_widget_uom/static/description/icon.png
  web_widget_uom/static/description/index.html
  web_widget_uom/static/src/js/widget.js
  web_widget_uom/tests/__init__.py
  web_widget_uom/tests/test_decimal_precision.py
  web_widget_uom/views/assets.xml
  web_widget_uom/views/uom_uom_views.xml
Labels: 14.0

#1135 Syncing from upstream OCA/web (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 15.0

#1136 Syncing from upstream OCA/web (16.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: 16.0

#1137 Syncing from upstream OCA/web (16.0)
  web_dark_mode/i18n/fr.po
  web_group_expand/i18n/pt_BR.po
  web_responsive/i18n/pt_BR.po
  web_timeline/i18n/pt_BR.po
Labels: 16.0

#1138 Syncing from upstream OCA/web (13.0)
  web_drop_target/i18n/it.po
Labels: 13.0

#1139 Syncing from upstream OCA/web (14.0)
  web_drop_target/i18n/it.po
  web_pwa_oca/i18n/es_AR.po
Labels: 14.0

#1140 Syncing from upstream OCA/web (15.0)
  README.md
  web_advanced_search/i18n/da.po
  web_advanced_search/i18n/de.po
  web_advanced_search/i18n/es.po
  web_advanced_search/i18n/fr.po
  web_advanced_search/i18n/hr.po
  web_advanced_search/i18n/it.po
  web_advanced_search/i18n/nl.po
  web_advanced_search/i18n/nl_NL.po
  web_advanced_search/i18n/pl.po
  web_advanced_search/i18n/pt.po
  web_advanced_search/i18n/pt_BR.po
  web_advanced_search/i18n/zh_CN.po
  web_drop_target/i18n/it.po
  web_ir_actions_act_view_reload/README.rst
  web_ir_actions_act_view_reload/__manifest__.py
  web_ir_actions_act_view_reload/i18n/web_ir_actions_act_view_reload.pot
  web_ir_actions_act_view_reload/i18n/zh_CN.po
  web_ir_actions_act_view_reload/models/ir_actions_act_view_reload.py
  web_ir_actions_act_view_reload/static/description/index.html
  web_pwa_oca/i18n/es_AR.po
Labels: 15.0

#1141 Syncing from upstream OCA/web (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml.rej
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  support_branding/README.rst
  support_branding/__manifest__.py
  support_branding/demo/ir_config_parameter_data.xml
  support_branding/static/description/index.html
  web_create_write_confirm/README.rst
  web_create_write_confirm/__manifest__.py
  web_create_write_confirm/i18n/web_create_write_confirm.pot
  web_create_write_confirm/static/description/index.html
  web_create_write_confirm/views/assets.xml
  web_create_write_confirm/views/popup_message.xml
  web_field_required_invisible_manager/README.rst
  web_field_required_invisible_manager/__manifest__.py
  web_field_required_invisible_manager/i18n/it.po
  web_field_required_invisible_manager/i18n/web_field_required_invisible_manager.pot
  web_field_required_invisible_manager/static/description/index.html
  web_field_required_invisible_manager/views/views.xml
  web_m2x_options_manager/README.rst
  web_m2x_options_manager/__manifest__.py
  web_m2x_options_manager/i18n/it.po
  web_m2x_options_manager/i18n/web_m2x_options_manager.pot
  web_m2x_options_manager/static/description/index.html
  web_m2x_options_manager/views/ir_model.xml
  web_no_bubble/README.rst
  web_no_bubble/__manifest__.py
  web_no_bubble/static/description/index.html
  web_no_bubble/views/web_no_bubble.xml
  web_pwa_oca/README.rst
  web_pwa_oca/__manifest__.py
  web_pwa_oca/static/description/index.html
  web_pwa_oca/views/res_config_settings_views.xml
  web_switch_context_warning/README.rst
  web_switch_context_warning/__manifest__.py
  web_switch_context_warning/static/description/index.html
  web_switch_context_warning/view/view.xml
Labels: 14.0
