Repository brain-tec/web, pull requests merged in 2023-03, with the labels that each got.

#1000 Syncing from upstream OCA/web (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_pivot_computed_measure/odoo/addons/web_pivot_computed_measure
  setup/web_pivot_computed_measure/setup.py
  web_pivot_computed_measure/README.rst
  web_pivot_computed_measure/__init__.py
  web_pivot_computed_measure/__manifest__.py
  web_pivot_computed_measure/i18n/ca.po
  web_pivot_computed_measure/i18n/es.po
  web_pivot_computed_measure/i18n/web_pivot_computed_measure.pot
  web_pivot_computed_measure/readme/CONTRIBUTORS.rst
  web_pivot_computed_measure/readme/DESCRIPTION.rst
  web_pivot_computed_measure/readme/ROADMAP.rst
  web_pivot_computed_measure/readme/USAGE.rst
  web_pivot_computed_measure/static/description/icon.png
  web_pivot_computed_measure/static/description/index.html
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.esm.js
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.scss
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.xml
  web_pivot_computed_measure/static/src/pivot/pivot_model.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_view.xml
  web_pivot_computed_measure/static/src/test/test.esm.js
  web_pivot_computed_measure/static/src/view.xml
  web_pivot_computed_measure/tests/__init__.py
  web_pivot_computed_measure/tests/res_users_fake.py
  web_pivot_computed_measure/tests/test_ui_pivot.py
Labels: 15.0

#1002 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_chatter_position/odoo/addons/web_chatter_position
  setup/web_chatter_position/setup.py
  web_chatter_position/README.rst
  web_chatter_position/__init__.py
  web_chatter_position/__manifest__.py
  web_chatter_position/i18n/web_chatter_position.pot
  web_chatter_position/models/__init__.py
  web_chatter_position/models/res_users.py
  web_chatter_position/readme/CONTRIBUTORS.rst
  web_chatter_position/readme/DESCRIPTION.rst
  web_chatter_position/readme/USAGE.rst
  web_chatter_position/static/description/icon.png
  web_chatter_position/static/description/index.html
  web_chatter_position/static/src/js/web_chatter_position.esm.js
  web_chatter_position/views/res_users.xml
  web_chatter_position/views/web.xml
Labels: 16.0

#1003 Syncing from upstream OCA/web (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  web_timeline/__manifest__.py
  web_timeline/static/src/js/timeline_renderer.js
Labels: 14.0

#1004 Syncing from upstream OCA/web (15.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
  web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss
  web_timeline/__manifest__.py
  web_timeline/static/src/js/timeline_renderer.js
Labels: 15.0

#1006 Syncing from upstream OCA/web (16.0)
  web_responsive/i18n/tr.po
Labels: 16.0

#1007 Syncing from upstream OCA/web (14.0)
  README.md
  web_m2x_options/__manifest__.py
  web_m2x_options/static/src/js/form.js
Labels: 14.0

#1008 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/static/src/components/control_panel/control_panel.scss
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: 16.0

#1009 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/static/src/components/control_panel/control_panel.scss
Labels: 16.0

#1010 Syncing from upstream OCA/web (15.0)
  .copier-answers.yml
Labels: 15.0

#1011 Syncing from upstream OCA/web (16.0)
  .copier-answers.yml
Labels: 16.0

#1012 Syncing from upstream OCA/web (12.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 12.0

#1013 Syncing from upstream OCA/web (13.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 13.0

#1014 Syncing from upstream OCA/web (16.0)
  web_chatter_position/i18n/fr.po
  web_responsive/i18n/fr.po
Labels: 16.0

#1015 Syncing from upstream OCA/web (14.0)
  README.md
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/readme/USAGE.rst
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_renderer.js
  web_widget_x2many_2d_matrix/static/src/js/abstract_view_matrix_limit_extend.js
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: 14.0

#1016 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_tree_many2one_clickable/odoo/addons/web_tree_many2one_clickable
  setup/web_tree_many2one_clickable/setup.py
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/__init__.py
  web_tree_many2one_clickable/__manifest__.py
  web_tree_many2one_clickable/i18n/web_tree_many2one_clickable.pot
  web_tree_many2one_clickable/i18n/zh_CN.po
  web_tree_many2one_clickable/readme/CONFIGURATION.rst
  web_tree_many2one_clickable/readme/CONTRIBUTORS.rst
  web_tree_many2one_clickable/readme/DESCRIPTION.rst
  web_tree_many2one_clickable/readme/ROADMAP.rst
  web_tree_many2one_clickable/readme/USAGE.rst
  web_tree_many2one_clickable/static/description/icon.png
  web_tree_many2one_clickable/static/description/index.html
  web_tree_many2one_clickable/static/img/clickable.gif
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.esm.js
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.scss
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.xml
Labels: 16.0

#1017 Syncing from upstream OCA/web (16.0)
  web_tree_many2one_clickable/i18n/zh_CN.po
Labels: 16.0

#1018 Syncing from upstream OCA/web (14.0)
  README.md
  support_branding/__manifest__.py
  support_branding/i18n/it.po
  support_branding/i18n/nl.po
  support_branding/i18n/sl.po
  support_branding/i18n/support_branding.pot
  support_branding/models/__init__.py
  support_branding/models/res_company.py
  support_branding/static/src/js/res_config_edition.js
  support_branding/static/src/js/support_branding.js
  support_branding/static/src/js/user_menu.js
  support_branding/tests/__init__.py
  support_branding/tests/test_support_branding.py
Labels: 14.0

#1019 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
Labels: 16.0

#1020 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/__manifest__.py
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: 16.0

#1021 Syncing from upstream OCA/web (14.0)
  web_m2x_options_manager/i18n/it.po
Labels: 14.0

#1022 [t136404] Add module web_advanced_search to project branch
  setup/web_advanced_search/odoo/addons/web_advanced_search
  setup/web_advanced_search/setup.py
  web_advanced_search/README.rst
  web_advanced_search/__init__.py
  web_advanced_search/__manifest__.py
  web_advanced_search/i18n/da.po
  web_advanced_search/i18n/de.po
  web_advanced_search/i18n/es.po
  web_advanced_search/i18n/fr.po
  web_advanced_search/i18n/hr.po
  web_advanced_search/i18n/it.po
  web_advanced_search/i18n/nl.po
  web_advanced_search/i18n/nl_NL.po
  web_advanced_search/i18n/pl.po
  web_advanced_search/i18n/pt.po
  web_advanced_search/i18n/pt_BR.po
  web_advanced_search/i18n/web_advanced_search.pot
  web_advanced_search/i18n/zh_CN.po
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/readme/DESCRIPTION.rst
  web_advanced_search/readme/HISTORY.rst
  web_advanced_search/readme/ROADMAP.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/description/icon.png
  web_advanced_search/static/description/index.html
  web_advanced_search/static/img/debug_mode.png
  web_advanced_search/static/src/js/RecordPicker.esm.js
  web_advanced_search/static/src/js/legacy/AdvancedFilterItem.esm.js
  web_advanced_search/static/src/js/legacy/CustomFilterItem.esm.js
  web_advanced_search/static/src/js/legacy/FilterMenu.esm.js
  web_advanced_search/static/src/js/owl/AdvancedFilterItem.esm.js
  web_advanced_search/static/src/js/owl/CustomFilterItem.esm.js
  web_advanced_search/static/src/js/owl/FilterMenu.esm.js
  web_advanced_search/static/src/js/utils.esm.js
  web_advanced_search/static/src/xml/AdvancedFilterItem.xml
  web_advanced_search/static/src/xml/CustomFilterItem.xml
  web_advanced_search/static/src/xml/FilterMenu.xml
Labels: 16.0.project_ms_665

#1024 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_no_bubble/odoo/addons/web_no_bubble
  setup/web_no_bubble/setup.py
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/es.po
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/readme/CONTRIBUTORS.rst
  web_no_bubble/readme/DESCRIPTION.rst
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
Labels: 16.0

#1025 Syncing from upstream OCA/web (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_time_range_menu_custom/odoo/addons/web_time_range_menu_custom
  setup/web_time_range_menu_custom/setup.py
  web_time_range_menu_custom/README.rst
  web_time_range_menu_custom/__init__.py
  web_time_range_menu_custom/__manifest__.py
  web_time_range_menu_custom/i18n/web_time_range_menu_custom.pot
  web_time_range_menu_custom/readme/CONTRIBUTORS.rst
  web_time_range_menu_custom/readme/DESCRIPTION.rst
  web_time_range_menu_custom/static/description/icon.png
  web_time_range_menu_custom/static/description/index.html
  web_time_range_menu_custom/static/src/js/date_selector.esm.js
  web_time_range_menu_custom/static/src/js/dates.esm.js
  web_time_range_menu_custom/static/src/scss/web_time_range_menu_custom.scss
  web_time_range_menu_custom/static/src/xml/comparison_menu.xml
  web_time_range_menu_custom/static/src/xml/date_selector.xml
  web_time_range_menu_custom/static/src/xml/filter_menu.xml
Labels: 15.0
