Repository brain-tec/web, pull requests merged in 2024-02, with the labels that each got.

#1207 Syncing from upstream OCA/web (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 13.0

#1208 Syncing from upstream OCA/web (16.0)
  web_dashboard_tile/i18n/it.po
Labels: 16.0

#1209 Syncing from upstream OCA/web (8.0)
  web_dashboard_tile/i18n/it.po
Labels: 8.0

#1210 Syncing from upstream OCA/web (16.0)
  web_dashboard_tile/i18n/it.po
  web_m2x_options/i18n/fr.po
Labels: 16.0

#1211 Syncing from upstream OCA/web (17.0)
  web_no_bubble/i18n/it.po
  web_refresher/i18n/ca.po
  web_refresher/i18n/de.po
  web_refresher/i18n/es.po
  web_refresher/i18n/fr.po
  web_refresher/i18n/hr.po
  web_refresher/i18n/pt_BR.po
  web_refresher/i18n/uk_UA.po
  web_responsive/i18n/ar.po
  web_responsive/i18n/ca.po
  web_responsive/i18n/da.po
  web_responsive/i18n/de.po
  web_responsive/i18n/es.po
  web_responsive/i18n/fr.po
  web_responsive/i18n/fr_FR.po
  web_responsive/i18n/hr.po
  web_responsive/i18n/nl.po
  web_responsive/i18n/pl.po
  web_responsive/i18n/pt.po
  web_responsive/i18n/pt_BR.po
  web_responsive/i18n/ru.po
  web_responsive/i18n/tr.po
  web_responsive/i18n/uk_UA.po
  web_responsive/i18n/zh_CN.po
Labels: 17.0

#1212 Syncing from upstream OCA/web (17.0)
  web_environment_ribbon/i18n/it.po
  web_refresher/i18n/it.po
  web_responsive/i18n/it.po
Labels: 17.0

#1213 Syncing from upstream OCA/web (12.0)
  README.md
  web_advanced_filter/README.rst
  web_advanced_filter/__manifest__.py
  web_advanced_filter/static/description/index.html
  web_advanced_filter/wizards/ir_filters_combine_with_existing.py
Labels: 12.0

#1214 Syncing from upstream OCA/web (17.0)
  web_refresher/i18n/es.po
  web_responsive/i18n/es.po
Labels: 17.0

#1215 Syncing from upstream OCA/web (12.0)
  README.md
  web_translate_dialog/README.rst
  web_translate_dialog/__manifest__.py
  web_translate_dialog/static/description/index.html
  web_translate_dialog/static/src/js/web_translate_dialog.js
Labels: 12.0

#1216 Syncing from upstream OCA/web (15.0)
  README.md
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/js/client_action_adapter.esm.js
  web_refresher/static/src/js/refresher.esm.js
Labels: 15.0

#1217 Syncing from upstream OCA/web (16.0)
  README.md
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/js/control_panel.esm.js
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/scss/refresher.scss
  web_refresher/static/src/xml/control_panel.xml
Labels: 16.0

#1218 Syncing from upstream OCA/web (12.0)
  web_responsive/i18n/it.po
Labels: 12.0

#1219 Syncing from upstream OCA/web (14.0)
  README.md
  web_dialog_size/i18n/it.po
  web_field_required_invisible_manager/README.rst
  web_field_required_invisible_manager/__manifest__.py
  web_field_required_invisible_manager/i18n/it.po
  web_field_required_invisible_manager/i18n/web_field_required_invisible_manager.pot
  web_field_required_invisible_manager/models/__init__.py
  web_field_required_invisible_manager/models/base.py
  web_field_required_invisible_manager/models/ir_model.py
  web_field_required_invisible_manager/models/ir_ui_view.py
  web_field_required_invisible_manager/static/description/index.html
  web_responsive/i18n/it.po
Labels: 14.0

#1220 Syncing from upstream OCA/web (16.0)
  web_responsive/i18n/it.po
Labels: 16.0

#1221 Syncing from upstream OCA/web (17.0)
  web_responsive/i18n/it.po
Labels: 17.0

#1222 Syncing from upstream OCA/web (14.0)
  web_field_required_invisible_manager/i18n/it.po
Labels: 14.0

#1223 Syncing from upstream OCA/web (16.0)
  README.md
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/src/views/fields/boolean/boolean_field.esm.js
Labels: 16.0

#1224 [t145928] Company CCS Style
  web_company_color/models/res_company.py
Labels: 16.0.project_ta_656

#1226 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_datepicker_fulloptions/odoo/addons/web_widget_datepicker_fulloptions
  setup/web_widget_datepicker_fulloptions/setup.py
  web_widget_datepicker_fulloptions/README.rst
  web_widget_datepicker_fulloptions/__init__.py
  web_widget_datepicker_fulloptions/__manifest__.py
  web_widget_datepicker_fulloptions/i18n/pt_BR.po
  web_widget_datepicker_fulloptions/i18n/web_widget_datepicker_fulloptions.pot
  web_widget_datepicker_fulloptions/readme/CONTRIBUTORS.rst
  web_widget_datepicker_fulloptions/readme/DESCRIPTION.rst
  web_widget_datepicker_fulloptions/static/description/change.png
  web_widget_datepicker_fulloptions/static/description/icon.png
  web_widget_datepicker_fulloptions/static/description/index.html
  web_widget_datepicker_fulloptions/static/src/js/web_widget_datepicker_fulloptions.esm.js
Labels: 16.0

#1228 Syncing from upstream OCA/web (15.0)
  README.md
  web_tree_dynamic_colored_field/README.rst
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/readme/USAGE.rst
  web_tree_dynamic_colored_field/static/description/index.html
Labels: 15.0

#1230 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
  web_responsive/static/src/components/chatter_topbar/chatter_topbar.xml
Labels: 16.0

#1231 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_pwa_oca/odoo/addons/web_pwa_oca
  setup/web_pwa_oca/setup.py
  web_pwa_oca/README.rst
  web_pwa_oca/__init__.py
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/controllers/service_worker.py
  web_pwa_oca/i18n/es.po
  web_pwa_oca/i18n/es_AR.po
  web_pwa_oca/i18n/it.po
  web_pwa_oca/i18n/pt_BR.po
  web_pwa_oca/i18n/web_pwa_oca.pot
  web_pwa_oca/models/__init__.py
  web_pwa_oca/models/res_config_settings.py
  web_pwa_oca/readme/CONFIGURE.rst
  web_pwa_oca/readme/CONTRIBUTORS.rst
  web_pwa_oca/readme/DESCRIPTION.rst
  web_pwa_oca/readme/INSTALL.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/readme/USAGE.rst
  web_pwa_oca/static/description/icon.png
  web_pwa_oca/static/description/index.html
  web_pwa_oca/static/description/pwa.png
  web_pwa_oca/static/img/icons/icon-128x128.png
  web_pwa_oca/static/img/icons/icon-144x144.png
  web_pwa_oca/static/img/icons/icon-152x152.png
  web_pwa_oca/static/img/icons/icon-192x192.png
  web_pwa_oca/static/img/icons/icon-256x256.png
  web_pwa_oca/static/img/icons/icon-512x512.png
  web_pwa_oca/static/img/icons/odoo_logo.svg
  web_pwa_oca/static/src/js/pwa_manager.js
  web_pwa_oca/static/src/js/webclient.js
  web_pwa_oca/static/src/js/worker/jquery-sw-compat.js
  web_pwa_oca/static/src/js/worker/pwa.js
  web_pwa_oca/templates/assets.xml
  web_pwa_oca/tests/__init__.py
  web_pwa_oca/tests/test_web_pwa_oca_controller.py
  web_pwa_oca/views/res_config_settings_views.xml
Labels: 16.0

#1232 Syncing from upstream OCA/web (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_custom_modifier/odoo/addons/web_custom_modifier
  setup/web_custom_modifier/setup.py
  web_custom_modifier/README.rst
  web_custom_modifier/__init__.py
  web_custom_modifier/__manifest__.py
  web_custom_modifier/i18n/fr.po
  web_custom_modifier/i18n/web_custom_modifier.pot
  web_custom_modifier/models/__init__.py
  web_custom_modifier/models/base.py
  web_custom_modifier/models/common.py
  web_custom_modifier/models/ir_ui_view.py
  web_custom_modifier/models/web_custom_modifier.py
  web_custom_modifier/readme/CONTEXT.md
  web_custom_modifier/readme/CONTRIBUTOR.md
  web_custom_modifier/readme/DESCRIPTION.md
  web_custom_modifier/readme/ROADMAP.md
  web_custom_modifier/readme/USAGE.md
  web_custom_modifier/security/ir.model.access.csv
  web_custom_modifier/static/description/button_modifier.png
  web_custom_modifier/static/description/contact_form_type_not_selected.png
  web_custom_modifier/static/description/contact_form_without_selection_item.png
  web_custom_modifier/static/description/custom_modifier_menu.png
  web_custom_modifier/static/description/custom_widget.png
  web_custom_modifier/static/description/excluded_groups.png
  web_custom_modifier/static/description/force_save_modifier.png
  web_custom_modifier/static/description/hide_selection_item_modifier.png
  web_custom_modifier/static/description/icon.png
  web_custom_modifier/static/description/index.html
  web_custom_modifier/static/description/new_custom_modifier.png
  web_custom_modifier/static/description/number_lines_per_page_modifier.png
  web_custom_modifier/static/description/optional_modifier.png
  web_custom_modifier/static/description/optional_modifier_applied.png
  web_custom_modifier/static/description/product_form.png
  web_custom_modifier/static/description/sale_order_with_limited_sol_per_page.png
  web_custom_modifier/static/description/task_form_with_custom_widget.png
  web_custom_modifier/tests/__init__.py
  web_custom_modifier/tests/test_view_rendering.py
  web_custom_modifier/utils.py
  web_custom_modifier/views/web_custom_modifier.xml
Labels: 14.0

#1233 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_pivot_computed_measure/odoo/addons/web_pivot_computed_measure
  setup/web_pivot_computed_measure/setup.py
  test-requirements.txt
  web_pivot_computed_measure/README.rst
  web_pivot_computed_measure/__init__.py
  web_pivot_computed_measure/__manifest__.py
  web_pivot_computed_measure/i18n/ca.po
  web_pivot_computed_measure/i18n/es.po
  web_pivot_computed_measure/i18n/web_pivot_computed_measure.pot
  web_pivot_computed_measure/readme/CONTRIBUTORS.rst
  web_pivot_computed_measure/readme/DESCRIPTION.rst
  web_pivot_computed_measure/readme/ROADMAP.rst
  web_pivot_computed_measure/readme/USAGE.rst
  web_pivot_computed_measure/static/description/icon.png
  web_pivot_computed_measure/static/description/index.html
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.esm.js
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.scss
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.xml
  web_pivot_computed_measure/static/src/helpers/utils.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_controller.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_model.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_renderer.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_view.xml
  web_pivot_computed_measure/static/src/test/test.esm.js
  web_pivot_computed_measure/static/src/view.xml
  web_pivot_computed_measure/tests/__init__.py
  web_pivot_computed_measure/tests/res_users_fake.py
  web_pivot_computed_measure/tests/test_ui_pivot.py
Labels: 16.0
