Repository brain-tec/web, pull requests merged in 2024-07, with the labels that each got.

#1312 Syncing from upstream OCA/web (17.0)
  README.md
  setup/_metapackage/pyproject.toml
  web_group_expand/README.rst
  web_group_expand/__init__.py
  web_group_expand/__manifest__.py
  web_group_expand/i18n/ca.po
  web_group_expand/i18n/de.po
  web_group_expand/i18n/es.po
  web_group_expand/i18n/it.po
  web_group_expand/i18n/nl.po
  web_group_expand/i18n/pt_BR.po
  web_group_expand/i18n/web_group_expand.pot
  web_group_expand/pyproject.toml
  web_group_expand/readme/CONTRIBUTORS.md
  web_group_expand/readme/DESCRIPTION.md
  web_group_expand/static/description/icon.png
  web_group_expand/static/description/index.html
  web_group_expand/static/src/js/list_controller.esm.js
  web_group_expand/static/src/xml/list_controller.xml
Labels: 17.0

#1313 Syncing from upstream OCA/web (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_notify_upgrade/odoo/addons/web_notify_upgrade
  setup/web_notify_upgrade/setup.py
  web_notify_upgrade/README.rst
  web_notify_upgrade/__init__.py
  web_notify_upgrade/__manifest__.py
  web_notify_upgrade/i18n/web_notify_upgrade.pot
  web_notify_upgrade/models/__init__.py
  web_notify_upgrade/models/ir_model.py
  web_notify_upgrade/readme/CONTRIBUTORS.rst
  web_notify_upgrade/readme/DESCRIPTION.rst
  web_notify_upgrade/static/description/icon.png
  web_notify_upgrade/static/description/index.html
Labels: 14.0

#1314 Syncing from upstream OCA/web (14.0)
  README.md
  web_timeline/README.rst
  web_timeline/__manifest__.py
  web_timeline/static/description/index.html
  web_timeline/static/src/js/timeline_view.js
Labels: 14.0

#1315 Syncing from upstream OCA/web (17.0)
  README.md
  setup/_metapackage/pyproject.toml
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__init__.py
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/i18n/es.po
  web_widget_domain_editor_dialog/i18n/it.po
  web_widget_domain_editor_dialog/i18n/web_widget_domain_editor_dialog.pot
  web_widget_domain_editor_dialog/i18n/zh_CN.po
  web_widget_domain_editor_dialog/pyproject.toml
  web_widget_domain_editor_dialog/readme/CONTRIBUTORS.md
  web_widget_domain_editor_dialog/readme/DESCRIPTION.md
  web_widget_domain_editor_dialog/readme/USAGE.md
  web_widget_domain_editor_dialog/static/description/icon.png
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/img/behaviour.gif
  web_widget_domain_editor_dialog/static/src/js/domain_field.esm.js
  web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.esm.js
Labels: 17.0

#1316 Syncing from upstream OCA/web (17.0)
  web_widget_domain_editor_dialog/i18n/es.po
  web_widget_domain_editor_dialog/i18n/zh_CN.po
Labels: 17.0

#1317 Syncing from upstream OCA/web (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_text_markdown/odoo/addons/web_widget_text_markdown
  setup/web_widget_text_markdown/setup.py
  web_widget_text_markdown/README.rst
  web_widget_text_markdown/__init__.py
  web_widget_text_markdown/__manifest__.py
  web_widget_text_markdown/demo/bootstrap_markdown.xml
  web_widget_text_markdown/i18n/web_widget_text_markdown.pot
  web_widget_text_markdown/readme/CONTRIBUTORS.rst
  web_widget_text_markdown/readme/CREDITS.rst
  web_widget_text_markdown/readme/DESCRIPTION.rst
  web_widget_text_markdown/readme/ROADMAP.rst
  web_widget_text_markdown/readme/USAGE.rst
  web_widget_text_markdown/static/description/icon.png
  web_widget_text_markdown/static/description/index.html
  web_widget_text_markdown/static/src/css/web_widget_text_markdown.css
  web_widget_text_markdown/static/src/js/web_widget_text_markdown.js
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.js
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.min.css
  web_widget_text_markdown/static/src/lib/marked.js
  web_widget_text_markdown/static/src/lib/showdown-footnotes.js
  web_widget_text_markdown/static/src/lib/showdown-table.js
  web_widget_text_markdown/static/src/lib/showdown-toc.js
  web_widget_text_markdown/static/src/lib/showdown.js
  web_widget_text_markdown/static/tests/js/web_widget_text_markdown.js
Labels: 15.0

#1318 Syncing from upstream OCA/web (17.0)
  README.md
  web_favicon/README.rst
  web_favicon/__manifest__.py
  web_favicon/models/res_company.py
  web_favicon/static/description/index.html
  web_favicon/tests/test_web_favicon.py
Labels: 17.0

#1319 [MIG] web_chatter_position
  web_chatter_position/README.rst
  web_chatter_position/__init__.py
  web_chatter_position/__manifest__.py
  web_chatter_position/i18n/ca.po
  web_chatter_position/i18n/de.po
  web_chatter_position/i18n/es.po
  web_chatter_position/i18n/fr.po
  web_chatter_position/i18n/hr.po
  web_chatter_position/i18n/it.po
  web_chatter_position/i18n/nl.po
  web_chatter_position/i18n/pt_BR.po
  web_chatter_position/i18n/tr.po
  web_chatter_position/i18n/web_chatter_position.pot
  web_chatter_position/models/__init__.py
  web_chatter_position/models/res_users.py
  web_chatter_position/pyproject.toml
  web_chatter_position/readme/CONTRIBUTORS.md
  web_chatter_position/readme/DESCRIPTION.md
  web_chatter_position/readme/USAGE.md
  web_chatter_position/static/description/icon.png
  web_chatter_position/static/description/index.html
  web_chatter_position/static/src/js/web_chatter_position.esm.js
  web_chatter_position/static/src/scss/form_controller.scss
  web_chatter_position/static/src/scss/form_renderer.scss
  web_chatter_position/views/res_users.xml
  web_chatter_position/views/web.xml
Labels: 17.0.project_ba_688

#1320 Syncing from upstream OCA/web (17.0)
  README.md
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
Labels: 17.0

#1321 Syncing from upstream OCA/web (15.0)
  README.md
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/readme/USAGE.rst
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: 15.0

#1322 Syncing from upstream OCA/web (17.0)
  README.md
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/i18n/ar.po
  web_responsive/i18n/ca.po
  web_responsive/i18n/da.po
  web_responsive/i18n/de.po
  web_responsive/i18n/es.po
  web_responsive/i18n/fr.po
  web_responsive/i18n/fr_FR.po
  web_responsive/i18n/hr.po
  web_responsive/i18n/it.po
  web_responsive/i18n/nl.po
  web_responsive/i18n/pl.po
  web_responsive/i18n/pt.po
  web_responsive/i18n/pt_BR.po
  web_responsive/i18n/ru.po
  web_responsive/i18n/tr.po
  web_responsive/i18n/uk_UA.po
  web_responsive/i18n/web_responsive.pot
  web_responsive/i18n/zh_CN.po
  web_responsive/models/res_users.py
  web_responsive/readme/CONTRIBUTORS.md
  web_responsive/readme/DESCRIPTION.md
  web_responsive/static/description/index.html
  web_responsive/static/img/redirecthome.gif
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
  web_responsive/tests/__init__.py
  web_responsive/tests/test_res_users.py
  web_responsive/views/res_users_views.xml
Labels: 17.0

#1323 Syncing from upstream OCA/web (16.0)
  README.md
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/js/control_panel.esm.js
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/xml/control_panel.xml
  web_refresher/static/src/xml/form_control_panel.xml
Labels: 16.0

#1324 Syncing from upstream OCA/web (17.0)
  README.md
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/scss/refresher.scss
Labels: 17.0

#1325 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
  web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss
Labels: 16.0

#1326 Syncing from upstream OCA/web (16.0)
  web_responsive/i18n/es.po
Labels: 16.0

#1328 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/i18n/ar.po
  web_responsive/i18n/ca.po
  web_responsive/i18n/da.po
  web_responsive/i18n/de.po
  web_responsive/i18n/es.po
  web_responsive/i18n/fr.po
  web_responsive/i18n/fr_FR.po
  web_responsive/i18n/hr.po
  web_responsive/i18n/it.po
  web_responsive/i18n/nl.po
  web_responsive/i18n/pl.po
  web_responsive/i18n/pt.po
  web_responsive/i18n/pt_BR.po
  web_responsive/i18n/ru.po
  web_responsive/i18n/tr.po
  web_responsive/i18n/web_responsive.pot
  web_responsive/i18n/zh_CN.po
  web_responsive/static/description/index.html
  web_responsive/static/src/components/chatter_topbar/chatter_topbar.xml
Labels: 16.0

#1329 Syncing from upstream OCA/web (17.0)
  web_m2x_options/i18n/ar.po
  web_m2x_options/i18n/de.po
  web_m2x_options/i18n/es.po
  web_m2x_options/i18n/es_BO.po
  web_m2x_options/i18n/fi.po
  web_m2x_options/i18n/fr.po
  web_m2x_options/i18n/hr.po
  web_m2x_options/i18n/it.po
  web_m2x_options/i18n/nl.po
  web_m2x_options/i18n/nl_NL.po
  web_m2x_options/i18n/pt_BR.po
  web_m2x_options/i18n/sl.po
  web_m2x_options/i18n/tr.po
  web_m2x_options/i18n/zh_CN.po
Labels: 17.0

#1330 Syncing from upstream OCA/web (15.0)
  README.md
  web_m2x_options/README.rst
  web_m2x_options/__manifest__.py
  web_m2x_options/static/src/js/form.js
Labels: 15.0

#1331 Syncing from upstream OCA/web (17.0)
  README.md
  setup/_metapackage/pyproject.toml
  web_field_tooltip/README.rst
  web_field_tooltip/__init__.py
  web_field_tooltip/__manifest__.py
  web_field_tooltip/i18n/fr.po
  web_field_tooltip/i18n/it.po
  web_field_tooltip/i18n/web_field_tooltip.pot
  web_field_tooltip/migrations/17.0.1.0.0/post-migrate.py
  web_field_tooltip/models/__init__.py
  web_field_tooltip/models/base.py
  web_field_tooltip/models/ir_http.py
  web_field_tooltip/models/ir_model_fields_tooltip.py
  web_field_tooltip/models/res_users.py
  web_field_tooltip/pyproject.toml
  web_field_tooltip/readme/CONTRIBUTORS.md
  web_field_tooltip/readme/DESCRIPTION.md
  web_field_tooltip/readme/ROADMAP.md
  web_field_tooltip/readme/USAGE.md
  web_field_tooltip/security/ir_model_access.xml
  web_field_tooltip/security/res_groups.xml
  web_field_tooltip/static/description/icon.png
  web_field_tooltip/static/description/index.html
  web_field_tooltip/static/src/views/form/form_controller.esm.js
  web_field_tooltip/static/src/views/form/form_label.esm.js
  web_field_tooltip/static/src/views/form/form_label.xml
  web_field_tooltip/tests/__init__.py
  web_field_tooltip/tests/test_web_field_tooltip.py
  web_field_tooltip/views/ir_model_fields_tooltip.xml
  web_field_tooltip/views/res_users.xml
Labels: 17.0
