Repository brain-tec/web, pull requests merged in 2024-06, with the labels that each got.

#1301 Syncing from upstream OCA/web (17.0)
  README.md
  setup/_metapackage/pyproject.toml
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__init__.py
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/i18n/ar.po
  web_widget_x2many_2d_matrix/i18n/de.po
  web_widget_x2many_2d_matrix/i18n/es.po
  web_widget_x2many_2d_matrix/i18n/fi.po
  web_widget_x2many_2d_matrix/i18n/fr.po
  web_widget_x2many_2d_matrix/i18n/hr.po
  web_widget_x2many_2d_matrix/i18n/it.po
  web_widget_x2many_2d_matrix/i18n/lt.po
  web_widget_x2many_2d_matrix/i18n/nl.po
  web_widget_x2many_2d_matrix/i18n/nl_NL.po
  web_widget_x2many_2d_matrix/i18n/pt_BR.po
  web_widget_x2many_2d_matrix/i18n/sl.po
  web_widget_x2many_2d_matrix/i18n/tr.po
  web_widget_x2many_2d_matrix/i18n/web_widget_x2many_2d_matrix.pot
  web_widget_x2many_2d_matrix/i18n/zh_CN.po
  web_widget_x2many_2d_matrix/pyproject.toml
  web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.md
  web_widget_x2many_2d_matrix/readme/DESCRIPTION.md
  web_widget_x2many_2d_matrix/readme/HISTORY.md
  web_widget_x2many_2d_matrix/readme/ROADMAP.md
  web_widget_x2many_2d_matrix/readme/USAGE.md
  web_widget_x2many_2d_matrix/static/description/icon.png
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/description/screenshot.png
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.scss
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.xml
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.xml
Labels: 17.0

#1302 Syncing from upstream OCA/web (16.0)
  README.md
  web_dialog_size/README.rst
  web_dialog_size/__manifest__.py
  web_dialog_size/static/description/index.html
  web_dialog_size/static/src/js/web_dialog_size.js
  web_dialog_size/static/src/xml/web_dialog_size.xml
Labels: 16.0

#1303 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_one2many_tree_line_duplicate/odoo/addons/web_widget_one2many_tree_line_duplicate
  setup/web_widget_one2many_tree_line_duplicate/setup.py
  web_widget_one2many_tree_line_duplicate/README.rst
  web_widget_one2many_tree_line_duplicate/__init__.py
  web_widget_one2many_tree_line_duplicate/__manifest__.py
  web_widget_one2many_tree_line_duplicate/i18n/web_widget_one2many_tree_line_duplicate.pot
  web_widget_one2many_tree_line_duplicate/readme/CONTRIBUTORS.rst
  web_widget_one2many_tree_line_duplicate/readme/DESCRIPTION.rst
  web_widget_one2many_tree_line_duplicate/readme/ROADMAP.rst
  web_widget_one2many_tree_line_duplicate/readme/USAGE.rst
  web_widget_one2many_tree_line_duplicate/static/description/icon.png
  web_widget_one2many_tree_line_duplicate/static/description/index.html
  web_widget_one2many_tree_line_duplicate/static/src/basic_relational_model/basic_relational_model.esm.js
  web_widget_one2many_tree_line_duplicate/static/src/legacy/basic_model/basic_model.js
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.esm.js
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.xml
Labels: 16.0

#1304 Syncing from upstream OCA/web (17.0)
  README.md
  requirements.txt
  setup/_metapackage/pyproject.toml
  web_widget_bokeh_chart/README.rst
  web_widget_bokeh_chart/__init__.py
  web_widget_bokeh_chart/__manifest__.py
  web_widget_bokeh_chart/i18n/it.po
  web_widget_bokeh_chart/i18n/web_widget_bokeh_chart.pot
  web_widget_bokeh_chart/i18n/zh_CN.po
  web_widget_bokeh_chart/pyproject.toml
  web_widget_bokeh_chart/readme/CONTRIBUTORS.md
  web_widget_bokeh_chart/readme/CREDITS.md
  web_widget_bokeh_chart/readme/DESCRIPTION.md
  web_widget_bokeh_chart/readme/INSTALL.md
  web_widget_bokeh_chart/readme/ROADMAP.md
  web_widget_bokeh_chart/readme/USAGE.md
  web_widget_bokeh_chart/static/description/example.png
  web_widget_bokeh_chart/static/description/icon.png
  web_widget_bokeh_chart/static/description/index.html
  web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.esm.js
  web_widget_bokeh_chart/static/src/js/web_widget_bokeh_json_chart.esm.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-api-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-gl-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-mathjax-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-tables-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-3.4.1.min.js
  web_widget_bokeh_chart/static/src/xml/bokeh.xml
Labels: 17.0

#1305 Syncing from upstream OCA/web (16.0)
  web_widget_one2many_tree_line_duplicate/i18n/it.po
Labels: 16.0

#1306 Syncing from upstream OCA/web (17.0)
  README.md
  web_favicon/README.rst
  web_favicon/__manifest__.py
  web_favicon/models/res_company.py
  web_favicon/static/description/index.html
Labels: 17.0

#1307 Syncing from upstream OCA/web (15.0)
  README.md
  web_filter_header_button/README.rst
  web_filter_header_button/__manifest__.py
  web_filter_header_button/static/description/index.html
  web_filter_header_button/static/src/control_panel/control_panel.xml
Labels: 15.0

#1308 Syncing from upstream OCA/web (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_one2many_tree_line_duplicate/odoo/addons/web_widget_one2many_tree_line_duplicate
  setup/web_widget_one2many_tree_line_duplicate/setup.py
  web_widget_one2many_tree_line_duplicate/README.rst
  web_widget_one2many_tree_line_duplicate/__init__.py
  web_widget_one2many_tree_line_duplicate/__manifest__.py
  web_widget_one2many_tree_line_duplicate/i18n/web_widget_one2many_tree_line_duplicate.pot
  web_widget_one2many_tree_line_duplicate/readme/CONTRIBUTORS.rst
  web_widget_one2many_tree_line_duplicate/readme/DESCRIPTION.rst
  web_widget_one2many_tree_line_duplicate/readme/ROADMAP.rst
  web_widget_one2many_tree_line_duplicate/readme/USAGE.rst
  web_widget_one2many_tree_line_duplicate/static/description/icon.png
  web_widget_one2many_tree_line_duplicate/static/description/index.html
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.esm.js
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.scss
Labels: 15.0

#1309 Syncing from upstream OCA/web (16.0)
  README.md
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
  web_responsive/views/web.xml
Labels: 16.0

#1310 [t150149] 19362 Company Color (CSS) Improvements
  web_company_color/models/res_company.py
Labels: 16.0.project_ta_656

#1311 [t150149][FIX] CQ
  web_company_color/models/res_company.py
  web_company_color/view/res_company.xml
Labels: 16.0.project_ta_656
