Repository brain-tec/web, pull requests merged in 2024-03, with the labels that each got.

#1234 Syncing from upstream OCA/web (14.0)
  web_custom_modifier/i18n/it.po
Labels: 14.0

#1235 Syncing from upstream OCA/web (13.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_session_auto_close/odoo/addons/web_session_auto_close
  setup/web_session_auto_close/setup.py
  web_session_auto_close/README.rst
  web_session_auto_close/__init__.py
  web_session_auto_close/__manifest__.py
  web_session_auto_close/i18n/web_session_auto_close.pot
  web_session_auto_close/readme/CONTRIBUTORS.rst
  web_session_auto_close/readme/DESCRIPTION.rst
  web_session_auto_close/readme/HISTORY.rst
  web_session_auto_close/readme/USAGE.rst
  web_session_auto_close/static/description/icon.png
  web_session_auto_close/static/description/index.html
  web_session_auto_close/static/src/js/bus_service.js
  web_session_auto_close/static/src/js/local_storage_mixin.js
  web_session_auto_close/static/src/js/session.js
  web_session_auto_close/static/src/js/web_client.js
  web_session_auto_close/views/assets_backend.xml
  web_session_auto_close/views/assets_common.xml
Labels: 13.0

#1236 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_send_message_popup/odoo/addons/web_send_message_popup
  setup/web_send_message_popup/setup.py
  web_send_message_popup/README.rst
  web_send_message_popup/__init__.py
  web_send_message_popup/__manifest__.py
  web_send_message_popup/i18n/fa.po
  web_send_message_popup/i18n/web_send_message_popup.pot
  web_send_message_popup/readme/CONTRIBUTORS.rst
  web_send_message_popup/readme/DESCRIPTION.rst
  web_send_message_popup/static/description/icon.png
  web_send_message_popup/static/description/index.html
  web_send_message_popup/static/src/models/chatter/chatter.esm.js
Labels: 16.0

#1237 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_widget_domain_editor_dialog/odoo/addons/web_widget_domain_editor_dialog
  setup/web_widget_domain_editor_dialog/setup.py
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__init__.py
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/i18n/es.po
  web_widget_domain_editor_dialog/i18n/web_widget_domain_editor_dialog.pot
  web_widget_domain_editor_dialog/i18n/zh_CN.po
  web_widget_domain_editor_dialog/readme/CONTRIBUTORS.rst
  web_widget_domain_editor_dialog/readme/DESCRIPTION.rst
  web_widget_domain_editor_dialog/readme/USAGE.rst
  web_widget_domain_editor_dialog/static/description/icon.png
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/img/behaviour.gif
  web_widget_domain_editor_dialog/static/src/js/domain_field.esm.js
  web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.esm.js
Labels: 16.0

#1238 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_disable_export_group/odoo/addons/web_disable_export_group
  setup/web_disable_export_group/setup.py
  web_disable_export_group/README.rst
  web_disable_export_group/__init__.py
  web_disable_export_group/__manifest__.py
  web_disable_export_group/i18n/es.po
  web_disable_export_group/i18n/hr.po
  web_disable_export_group/i18n/it.po
  web_disable_export_group/i18n/pt.po
  web_disable_export_group/i18n/web_disable_export_group.pot
  web_disable_export_group/i18n/zh_CN.po
  web_disable_export_group/models/__init__.py
  web_disable_export_group/models/ir_http.py
  web_disable_export_group/models/models.py
  web_disable_export_group/readme/CONFIGURE.rst
  web_disable_export_group/readme/CONTRIBUTORS.rst
  web_disable_export_group/readme/DESCRIPTION.rst
  web_disable_export_group/readme/USAGE.rst
  web_disable_export_group/security/groups.xml
  web_disable_export_group/security/ir.model.access.csv
  web_disable_export_group/static/description/icon.png
  web_disable_export_group/static/description/index.html
  web_disable_export_group/static/src/js/abstract_controller.esm.js
  web_disable_export_group/static/src/js/list_controller.esm.js
  web_disable_export_group/static/src/xml/export_xls_views.xml
  web_disable_export_group/static/tests/web_disable_export_group_tour.esm.js
  web_disable_export_group/tests/__init__.py
  web_disable_export_group/tests/test_tour.py
  web_pivot_computed_measure/i18n/it.po
  web_send_message_popup/i18n/it.po
  web_widget_domain_editor_dialog/i18n/it.po
Labels: 16.0

#1241 [t145928][FIX] styles
  web_company_color/models/res_company.py
Labels: 16.0.project_ta_656

#1242 Syncing from upstream OCA/web (15.0)
  README.md
  web_drop_target/README.rst
  web_drop_target/__manifest__.py
  web_drop_target/static/description/index.html
  web_drop_target/static/src/js/web_drop_target.js
Labels: 15.0

#1243 Syncing from upstream OCA/web (11.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_clickjack_protection/odoo/addons/web_clickjack_protection
  setup/web_clickjack_protection/setup.cfg
  setup/web_clickjack_protection/setup.py
  web_clickjack_protection/README.rst
  web_clickjack_protection/__init__.py
  web_clickjack_protection/__manifest__.py
  web_clickjack_protection/i18n/web_clickjack_protection.pot
  web_clickjack_protection/readme/CONTRIBUTORS.rst
  web_clickjack_protection/readme/DESCRIPTION.rst
  web_clickjack_protection/static/description/icon.png
  web_clickjack_protection/static/description/index.html
  web_clickjack_protection/views/web_assets.xml
Labels: 11.0

#1244 Syncing from upstream OCA/web (12.0)
  README.md
  web_widget_image_url/README.rst
  web_widget_image_url/__manifest__.py
  web_widget_image_url/static/description/index.html
  web_widget_image_url/static/src/xml/web_widget_image_url.xml
Labels: 12.0

#1246 Syncing from upstream OCA/web (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_tooltip_field/odoo/addons/web_tooltip_field
  setup/web_tooltip_field/setup.py
  web_tooltip_field/README.rst
  web_tooltip_field/__init__.py
  web_tooltip_field/__manifest__.py
  web_tooltip_field/i18n/web_tooltip_field.pot
  web_tooltip_field/models/__init__.py
  web_tooltip_field/models/ir_model_fields_help_tooltip.py
  web_tooltip_field/patch.py
  web_tooltip_field/readme/CONTRIBUTORS.rst
  web_tooltip_field/readme/CREDITS.rst
  web_tooltip_field/readme/USAGE.rst
  web_tooltip_field/security/ir.model.access.csv
  web_tooltip_field/static/description/icon.png
  web_tooltip_field/tests/__init__.py
  web_tooltip_field/tests/test_field.py
  web_tooltip_field/views/ir_model_fields_help_tooltip_view.xml
Labels: 14.0

#1247 Syncing from upstream OCA/web (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_select_all_companies/odoo/addons/web_select_all_companies
  setup/web_select_all_companies/setup.py
  web_select_all_companies/README.rst
  web_select_all_companies/__init__.py
  web_select_all_companies/__manifest__.py
  web_select_all_companies/i18n/fr.po
  web_select_all_companies/i18n/web_select_all_companies.pot
  web_select_all_companies/readme/CONTRIBUTORS.rst
  web_select_all_companies/readme/DESCRIPTION.rst
  web_select_all_companies/static/description/icon.png
  web_select_all_companies/static/description/index.html
  web_select_all_companies/static/description/select_all_companies.gif
  web_select_all_companies/static/src/js/switch_all_company_menu.esm.js
  web_select_all_companies/static/src/scss/switch_all_company_menu.scss
  web_select_all_companies/static/src/xml/switch_all_company_menu.xml
Labels: 15.0

#1248 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_copy_confirm/odoo/addons/web_copy_confirm
  setup/web_copy_confirm/setup.py
  setup/web_widget_image_webcam/odoo/addons/web_widget_image_webcam
  setup/web_widget_image_webcam/setup.py
  web_copy_confirm/README.rst
  web_copy_confirm/__init__.py
  web_copy_confirm/__manifest__.py
  web_copy_confirm/i18n/de.po
  web_copy_confirm/i18n/web_copy_confirm.pot
  web_copy_confirm/readme/CONTRIBUTORS.rst
  web_copy_confirm/readme/DESCRIPTION.rst
  web_copy_confirm/readme/HISTORY.rst
  web_copy_confirm/static/description/icon.png
  web_copy_confirm/static/description/index.html
  web_copy_confirm/static/src/js/web_copy_confirm.esm.js
  web_copy_confirm/static/tests/confirm_tests.js
  web_widget_image_webcam/README.rst
  web_widget_image_webcam/__init__.py
  web_widget_image_webcam/__manifest__.py
  web_widget_image_webcam/i18n/es.po
  web_widget_image_webcam/i18n/web_widget_image_webcam.pot
  web_widget_image_webcam/models/__init__.py
  web_widget_image_webcam/models/ir_config_parameter.py
  web_widget_image_webcam/readme/CONFIGURE.rst
  web_widget_image_webcam/readme/CONTRIBUTORS.rst
  web_widget_image_webcam/readme/DESCRIPTION.rst
  web_widget_image_webcam/static/description/icon.png
  web_widget_image_webcam/static/description/index.html
  web_widget_image_webcam/static/src/css/web_widget_image_webcam.css
  web_widget_image_webcam/static/src/img/webcam_placeholder.png
  web_widget_image_webcam/static/src/js/webcam_widget.js
  web_widget_image_webcam/static/src/lib/webcam.js
  web_widget_image_webcam/static/src/lib/webcam.swf
  web_widget_image_webcam/static/src/xml/web_widget_image_webcam.xml
Labels: 16.0

#1250 Syncing from upstream OCA/web (16.0)
  web_copy_confirm/i18n/it.po
  web_widget_image_webcam/i18n/it.po
Labels: 16.0

#1251 Syncing from upstream OCA/web (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/web_hide_field_with_key/odoo/addons/web_hide_field_with_key
  setup/web_hide_field_with_key/setup.py
  web_hide_field_with_key/README.rst
  web_hide_field_with_key/__init__.py
  web_hide_field_with_key/__manifest__.py
  web_hide_field_with_key/i18n/web_hide_field_with_key.pot
  web_hide_field_with_key/readme/CONTRIBUTORS.rst
  web_hide_field_with_key/readme/DESCRIPTION.rst
  web_hide_field_with_key/readme/USAGE.rst
  web_hide_field_with_key/static/description/icon.png
  web_hide_field_with_key/static/description/index.html
  web_hide_field_with_key/static/src/js/hide_custom_hidden_fields.js
Labels: 16.0

#1252 Syncing from upstream OCA/web (15.0)
  README.md
  web_pivot_computed_measure/README.rst
  web_pivot_computed_measure/__manifest__.py
  web_pivot_computed_measure/static/description/index.html
  web_pivot_computed_measure/static/src/pivot/pivot_renderer.esm.js
Labels: 15.0

#1253 Syncing from upstream OCA/web (17.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  .ruff.toml
Labels: 17.0
